name: export_firebase_csv
homepage: https://github.com/zeymermontes/export_firebase_csv
description: Una librería Flutter que realiza exportación a CSV desde Firestore.
version: 1.0.6

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: '>=2.5.0 <5.0.0'
  intl: '>=0.17.0'
  download: ^1.0.0

environment:
  sdk: ">=2.12.0 <4.0.0"

example:
  main: example/main.dart

